### ISSUE TITLE
Script to manually add thumbnails

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/manual-data-ingest#101]
We will receive multiple image files that will be named with a specimen id (e.g. `VAN0003-LI-3.jpg` or `UFL0023-SP-4-2.xxx`)

Create a script to upload these files to the associated specimen via the entity-api and or ingest-api.

**Comment by yuanzhou** [comment]
There are some scripts I used earlier for registering thumbnails on Datasets: https://github.com/hubmapconsortium/manual-data-ingest/tree/master/ingest-thumbnails I had to parse the IDs from image file names, so this can be different for this issue. 

For sample, the similar field can is defined in entity-api: https://github.com/hubmapconsortium/entity-api/blob/main/src/schema/provenance_schema.yaml#L687

When registering a new thumbnail for a given sample, we'll need to 

1. upload the thumbnail image via ingest-api's and get back the temp file id
2. update the target entity via entity-api by using `thumbnail_file_to_add` field, which calls uuid-api to generate the file UUID then ingest-api to commit the file to final destination on the file system. The file info also gets stored in Neo4j.
3. index the doc to Elasticsearch via search-api (if needed)

**Comment by shirey** [comment]
@kburke 
  - The files can be named with UUID, HuBMAP ID or Submission ID- we should just make a call to UUID service to resolve any ID to UUID- this call will also validate that it is a good id and exists.
  - The existing thumbnail files in the database are likely for Datasets, not Samples.  For this particular import task we should check to make sure that the thumbnail files are being added to a Sample (not Donor, Dataset or any other type of entity)
  - We don't need to constrain to any particular file extension
  - Only one thumbnail is allowed per Sample.  I would check the Sample that the thumbnail will be added to to make sure it doesn't already have a thumbnail and report an error for that Sample/thumbnail.  Then for Samples with existing thumbnails we'll have to go back to the data provider and ask if they want it to be replaced.  I don't think we need to waste time spinning on checking across the file set that we're given for dupes.

**Comment by kburke** [comment]
Thanks @shirey
Just figuring out a bit myself, and it looks like SUBMISSION_IDs are only on the SAMPLEs in the ancestor stack of a typical file with a name like "thumb".
![image](https://user-images.githubusercontent.com/209327/178807977-d7bd7600-38c3-47ca-a045-fb681cdf8a70.png)

I remember you had some regrets about SUBMISSION_ID accommodations, and it looks like most are on SAMPLEs with a few hundred on DONORs, but I'm not sure if that is a constraint until I look around.

I'll run with your guidance...thanks again!

**Comment by kburke** [comment]
@shirey 

re: "The files can be named with UUID, HuBMAP ID or Submission ID..."
Will that be a HuBMAP ID with periods in it, like HBM769.NLGR.528 rather than 769NLGR528?  I need to find a **reliable spot & delimiting character to split the filename**.
I was aiming for _entityIdentifierWithNoPeriods.whateverElseTheyWant.extension_
But if there are periods in the HuBMAP ID, maybe I assume it is only _entityIdentifierPossiblyWithPeriods.extension_?  

also re: your 4th point above on entities that already have a thumbnail
This will cover if they add a file to the same entity using two different identifiers as well e.g.
I don't have to figure out HBM769.NLGR.528.png and 015ee234392256bfdb315299622ccb87.gif would modify the same entity.  I can set it to one, then warn them the second failed, right?

**Comment by shirey** [comment]
@kburke Yes, periods will be present in the id when someone sends a "HuBMAP ID"

RE: comment about the 4th point- correct- set the first one then warn about the second one.
