### ISSUE TITLE
Next round of DOIs for ASCT+B

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/manual-data-ingest#108]
Create DOIs based on the attached XML files.

**Comment by shirey** [comment]
[Borner_xml-7-16-2022-20220717T015824Z-001.zip](https://github.com/hubmapconsortium/manual-data-ingest/files/9133486/Borner_xml-7-16-2022-20220717T015824Z-001.zip)

**Comment by emquardokus** [comment]
@yuanzhou can you let us know when this will be done? thanks

**Comment by yuanzhou** [comment]
@emquardokus I've finished registering the 92 DOIs. Also verified that the redirection via entity-api works too.

**Comment by emquardokus** [comment]
There were 93 xml files in the .zip (see screenshot) (also present in our github repo) I've uploaded the one that was missed  in slack because github comment says it doesn't support this file type (weirdly). For placenta full term asct+B table
<img width="265" alt="Screen Shot 2022-07-27 at 3 14 07 PM" src="https://user-images.githubusercontent.com/47257000/181353959-b9d74d5d-4a41-4e95-a37b-7cbf229fbcd3.png">

**Comment by yuanzhou** [comment]
The one you posted on slack is already there: https://hubmapconsortium.github.io/ccf-releases/v1.2/docs/asct-b/placenta-full-term.html must be a different one missing
