### ISSUE TITLE
Publish U.CONN / Scripps RNA-seq data

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/manual-data-ingest#122]
Approval received from M.O. of Scripps to publish 6 RNA-seq datasets:

Primary Dataset	Derived Dataset
HBM837.FPWJ.865	HBM837.KRCD.342 | Note: an additional derived dataset (HBM993.PKVP.976) was accidentally created during pipeline processing. It will be submitted for deletion.
HBM233.CCCX.767	HBM852.CQCN.957 
HBM938.GJXR.224	HBM247.ZGJR.925
HBM756.PWKH.456	HBM767.CHDG.359
HBM599.GLRZ.888	HBM825.VPHH.585
HBM743.FBJP.586	HBM237.QHSL.933

**Comment by shirey** [comment]
@pecan88 @bhonick (@AlanSimmons  Only FYI until we can get the files to extract the donor metadata from) This data doesn't have any associated donor or sample metadata

We'll need donor metadata for the following donors before we can publish the above data:
  HBM783.WMTK.547	UCONN0011
  HBM993.XNPC.882	UCONN0012
  HBM697.KHFG.273	UCONN0013
  HBM569.GPRT.686	UCONN0014
  HBM475.LQWJ.329	UCONN0015
  HBM824.KJWW.778	UCONN0016

We should get metadata for the following tissue samples (seems like we've been publishing without sample metadata, but we should get it because we eventually need to get it for samples associated with any published data):
UCONN0016-RN-1 /  HBM499.GTSX.965
UCONN0011-RN-1 / HBM949.GVHP.463  
UCONN0013-RN-1 / HBM438.NWVX.837  
UCONN0012-RN-1 / HBM535.CKQS.877  
UCONN0014-LN-1 / HBM597.GXTC.432  
UCONN0015-RN-1 / HBM754.PJCB.873  
UCONN0015-RN-1 / HBM754.PJCB.873  
UCONN0014-LN-1 / HBM597.GXTC.432  
UCONN0012-RN-1 / HBM535.CKQS.877  
UCONN0013-RN-1 / HBM438.NWVX.837  
UCONN0016-RN-1 / HBM499.GTSX.965  
UCONN0011-RN-1 / HBM949.GVHP.463

**Comment by pecan88** [comment]
I reached out to M.O. requesting the donor & sample information for the entities listed above.  Looped in BH & AS in case they have questions.

**Comment by shirey** [comment]
@pecan88 / @bhonick  / @AlanSimmons These have been published
