### ISSUE TITLE
SNARE-seq data corrections

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/manual-data-ingest#40]
Data Type = snATAC-seq (SNARE-seq2). Should be "snRNA-seq (SNARE-seq2)"

HBM759.ZKDS.894
HBM342.MWMW.936
HBM393.NWNB.684
HBM742.GTJJ.334
HBM422.MKWK.448
HBM924.DSPX.449
HBM276.BCVG.232
HBM975.WHWM.552
HBM984.LZDJ.635
HBM444.BXPJ.728
HBM335.XXBG.857
HBM266.ZBKL.396
HBM585.GLSD.853
HBM557.KNTT.394
HBM257.JTGD.599
HBM656.KZXP.658
HBM562.WZFC.994
HBM379.ZGKM.223
HBM296.PCFN.989
HBM683.DSMM.562
HBM938.FTBC.347
HBM882.XFHR.889
HBM265.NXDR.935
HBM238.MHWZ.654
HBM678.FRJC.827
HBM363.NSBV.432
HBM442.HSFZ.838
HBM922.KSKR.637
HBM386.CVHG.956
HBM428.GPCD.698
HBM539.MKQD.956
HBM396.QSCB.763
HBM882.KDTH.685
HBM833.HFSG.364
HBM757.DZKS.993
HBM398.CFZH.458
HBM257.DBNG.933
HBM695.CKJX.997
HBM775.RVQX.376
HBM935.CNXT.255
HBM659.WFXT.729
HBM872.JGDD.956
HBM769.BDBL.437
HBM359.CQKZ.649
HBM459.BBRT.432
HBM375.KNVL.645
HBM727.FSWS.736
HBM723.QMLJ.829
HBM548.WNVT.322
HBM475.NWHG.922
HBM522.LXLF.753
HBM687.DTXP.559
HBM983.QHFB.659
HBM834.TDFD.294
HBM384.BWTV.862
HBM735.LWRH.779
HBM953.HGVS.696
HBM398.ZSNW.578
HBM466.RBPX.375
HBM587.JPLF.798
HBM788.XWPV.347
HBM959.XNWL.627
HBM446.FXTJ.757
HBM766.PSCS.545
HBM368.QPXJ.543
HBM245.VSKK.846
HBM368.FDDS.927
HBM746.WTMD.298
HBM725.NLKP.539
HBM523.FKWF.269
HBM846.NMQR.693
HBM584.ZTDX.845
HBM882.NBFK.489
HBM886.SLWK.262
HBM759.ZKDS.894

**Comment by shirey** [comment]
Done.  Two things to check:
 - The above list includes HBM759.ZKDS.894 twice, for 75 total (only 74 changed because of the duplicate)- is there one missing that the duplicate replace?
  - I changed the data type code to `SNARE-RNAseq2`, the gives the human readable form of "snRNAseq (SNARE-seq2)", without the dash in snRNA-seq as specified above- is this correct?
